title: Intro to Javascript
description: If you are looking for a quick and fun introduction to JS, you've found it. This course will help you create your own animations.
template:
  name: js-animation
  repo: javascript-animations-template
helpUrl: Khan Academy video
helpText: https://www.youtube.com/embed/us3_U9xnttc
preferences:
  - type: dropdown
    name: gitTool
    label: Preferred Git tool
    description: Which Git tool would you perfer?
    options:
      - label: GitHub.com
        value: dotcom
      - label: VS Code
        value: visual-studio
before:
  - type: createPullRequest
    title: Create a car
    head: create-car
    base: animate-car
    body: 1-welcome.md  
steps:
  - title: Introduction and creation
    description: Create a car that is used in the animations
    event: 
      - pull_request.push
      - pull_request.close
    actions:
          
