title: Intro to Javascript
description: If you are looking for a quick and fun introduction to JS, you've found it. This course will help you create your own animations.
template:
  name: js-animation
  repo: javascript-animations-template
helpUrl: Khan Academy video
helpText: https://www.youtube.com/embed/us3_U9xnttc
preferences:
  - type: dropdown
    name: gitTool
    label: Preferred Git tool
    description: Which Git tool would you perfer?
    options:
      - label: GitHub.com
        value: dotcom
      - label: VS Code
        value: visual-studio
  - type: dropdown
    name: language
    label: Preferred Language
    description: Which language would you perfer?
    options:
      - label: English
        value: en
      - label: 中文
        value: cn
tags: [
  "JavaScript", "HTML", "CSS"
]
before:
  - type: updateBranchProtection
    branch: main
    required_pull_request_reviews:
      include_admins: true
  - type: createPullRequest
    title: Create a car
    head: create-car
    base: animate-car
    body: 1-welcome.md  
steps:
  - title: Introduction and creation
    description: Create a car that is used in the animations
    event: pull_request.open
    actions:
          
